<?php



namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\School;

class SchoolSeeder extends Seeder
{
    public function run()
    {
        $schoolNames = [
    'Divine Word High School - Dana-ili Campus',
    'Lyceum of Abulug',
    'F.L. Vargas College',
    'Lyceum of Alcala, Inc.',
    'St. Philomene of Alcala, Inc.',
    'Allacapan Institute',
    'Our Lady of Victories Academy',
    'Cagayan Valley Institute',
    'Lyceum of Aparri',
    'St. Paul School of Aparri',
    'St. Joseph\'s College of Baggao, Inc.',
    'Northern Cagayan Colleges Foundation, Inc.',
    'Quezon Colleges of the North',
    'Northeastern Academy',
    'Lyceum of Camiguin',
    'Lyceum of Camalaniugan',
    'Academy of St. Joseph',
    'Our Lady of Snows Academy, Inc.',
    'Northern Philippines Academy',
    'St. Catherine\'s Academy',
    'St. Anthony\'s Academy - Gonzaga',
    'Saint James Academy of Iguig, Inc.',
    'Lyceum of Lal-lo',
    'Lasam Academy Incorporated',
    'San Lorenzo Ruiz Educational Institute, Inc.',
    'Pamplona Institute',
    'San Jacinto Seminary',
    'International School of Asia and the Pacific-Cagayan',
    'Our Lady of Piat High School',
    'Piat Academy',
    'Saint Francis Academy-Rizal',
    'Divine Word High School - Sanchez Mira',
    'Namuac Academy',
    'Thoburn Memorial Academy',
    'St. Anthony\'s College',
    'Saint Francis Academy',
    'Veridiano Academy Foundation',
    'San Vicente Institute of Solana, Inc.',
    'Lyceum of Tuao',
    'University of Cagayan Valley',
    'University of Saint Louis',
    'St. Paul University Philippines',
    'AMA Computer College-Tuguegarao City',
    'Maila Rosario College',
    'STI College - Tuguegarao',
    'City Technological Institute',
    'Cagayan Metropolitan Institute of Technology, Inc.',
    'International School of Asia and the Pacific - Atulayan',
    'Khan\'s Maritime Academy of the Philippines',
    'John Wesley College',
    'F. L. Vargas College',
    'Dalton Academy',
    'Northeast Luzon Adventist College',
    'School of Our Lady of Atocha',
    'Top Achievers Private School, Inc.',
    'La Salette of Aurora, Inc.',
    'St. Ferdinand College, Inc. - Cabagan',
    'La Salette of Cabatuan',
    'Philippine Yuh Chiau School',
    'Isabela College of Arts and Technology',
    'Metropolitan Bible Baptist Learning Center, Inc.',
    'Centro De Cultura',
    'Isabela Colleges Inc.',
    'Merry Sunshine Montessori School',
    'Nan Sing School of Cauayan City, Inc.',
    'Our Lady of the Pillar College-Cauayan City',
    'College of Business Education Science and Technology, Inc',
    'East Asia International Systems College',
    'Saint Clare College of Region 02, Inc.',
    'University of Perpetual Help System Laguna-JONELTA',
    'Children of Lourdes Academy-Cauayan Inc.',
    'Infant Jesus Montessori School, Inc.',
    'Santiago Cultural Institute',
    'University of La Salette, Inc.',
    'Sistech College of Santiago City, Inc.',
    'AMA Computer College-Santiago City',
    'Patria Sable Corpus College',
    'Children First School',
    'St. John Berchmans High School Inc.',
    'Magsaysay Memorial High School',
    'School of St. Joseph the Worker-Echague',
    'St. Dominic Human Development Center, Inc.',
    'Casa Del Niño Montessori School of Ilagan',
    'Central Isabela Christian Academy',
    'St. Ferdinand College, Inc. - Ilagan Campus',
    'Miracle Light Christian Academy',
    'Children\'s Learning and Development Center Foundation, Incorporation',
    'La Salette of Jones, Inc.',
    'Mallig Plains College',
    'School of St. Joseph (Naguilian, Isabela), Inc.',
    'La Salette of Quezon, Inc',
    'Wonderful Grace Learning Center',
    'JET Montessori of Ramon, Inc.',
    'La Salette of Ramon, Inc.',
    'Lord Reigns Christian Academy',
    'Alvarez-Ramales School Foundation, Inc.',
    'La Salette of Roxas College, Inc.',
    'Casa Del Niño Montessori School of Roxas',
    'Southern Isabela Academy, Inc.',
    'Our Lady of the Pillar College-San Manuel',
    'Alejandrino Family Learning Center',
    'Saint Thomas Montessori De San Mariano, Inc.',
    'Eveland Christian College. Inc.',
    'La Salette of San Mateo',
    'Northern Isabela Academy, Inc.',
    'School of Saint Matthias',
    'Advance Montessori Education Center of Isabela',
    'STI - Cauayan',
    'Northeastern College',
    'Cagayan Valley Computer & Information Technology College (CVCITC)',
    'STI College - Santiago',
    'STI Ilagan',
    'HG Baquiran College',
    'Nueva Vizcaya Institute',
    'St. Teresita\'s Academy of Aritao, Inc.',
    'Southern Cagayan Valley School of Technology, Inc.',
    'Saint Jerome\'s Academy',
    'Saint Catherine\'s School',
    'King\'s College of the Philippines, Inc.',
    'Nueva Vizcaya State University',
    'Saint Mary\'s University',
    'Sierra College',
    'Our Lady of Peace and Good Voyage Institute of Technology, Inc.',
    'Nueva Vizcaya Bright Child School, Inc.',
    'PLT College, Inc.',
    'Saint Joseph School',
    'Camella SNV School',
    'Aldersgate College',
    'Saint Louis School of Solano',
    'Our Lady of Fatima School of Villaverde',
    'Saint Mark\'s School',
    'Saint Mary\'s Academy',
    'Quirino State University-Main Campus, Diffun',
    'Saint Vincent School',
    'Maddela Marvelous Grace Christian School, Inc.',
    'Sacred Heart High School of Itogon, Inc.',
    'Philippine BELL International School',
    'BVS College',
    'Philippine Nazarene College',
    'Concordia College of Benguet, Inc.',
    'Cordillera Career Development College',
    'HOPE Christian Academy',
    'San Jose School of La Trinidad, Inc',
    'Star Colleges',
    'King\'s College of the Philippines',
    'Northskills Polytechnic College, Inc.',
    'Benguet State University-Secondary Lab School',
    'Immaculate Conception School',
    'The Ifugao Academy, Inc.',
    'St. Joseph\'s School',
    'Riverview Polytechnic and Academic School, Inc.',
    'Don Bosco High School',
    'San Francisco High School',
    'Assumption Academy',
    'St. Paul\'s Memorial School of Kalinga, Inc.',
    'St. Theresita High School of Salegseg, Inc.',
    'International School of Asia and the Pacific-Kalinga Campus',
    'Cordillera A+ Computer Technology College',
    'Saint Tonis College, Inc.',
    'St. Theresita High School - Tabuk',
    'Tabuk Institute',
    'Saint William\'s Academy',
    'Kalinga Colleges of Science and Technology',
    'Kalinga-Apayao State College',
    'St. Theresita\'s School of Lubuagan, Inc.',
    'St. Theresita High School - Pinukpuk',
    'Saint Michael\'s Academy, Rizal, Inc.',
    'St. Theresita\'s High School - Tinglayan',
    'Bauko Catholic School',
    'St. James High School of Mountain Province Inc.',
    'Saint Vincent\'s School',
    'XiJEN College of Mountain Province, Inc.',
    'Saint Mary\'s School of Sagada'
];


        foreach ($schoolNames as $name) {
            School::firstOrCreate(['school_name' => $name]);
        }
    }
}

