INSERT INTO tbl_questions VALUES("1","1","Verbal","Choose the words that <i>best</i> complete this sentence: <br> _________ I was nervous, I had a _________","Although -- quiet","When --- sad","After --- jittery","If ---- reasonable","Although --- quiet","Where --- humorous","Verbal Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("2","3","Verbal","<img src=images/questions/2_q.jpg>","<img src=images/questions/2_e.jpg>","<img src=images/questions/2_a.jpg>","<img src=images/questions/2_b.jpg>","<img src=images/questions/2_c.jpg>","<img src=images/questions/2_d.jpg>","<img src=images/questions/2_e.jpg>","Verbal Comprehension");<|||||||>
INSERT INTO tbl_questions VALUES("3","3","NonVerbal","<img src=images/questions/3_q.jpg>","<img src=images/questions/3_d.jpg>","<img src=images/questions/3_a.jpg>","<img src=images/questions/3_b.jpg>","<img src=images/questions/3_c.jpg>","<img src=images/questions/3_d.jpg>","<img src=images/questions/3_e.jpg>","Quantitative Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("4","3","NonVerbal","<img src=images/questions/4_q.jpg>","<img src=images/questions/4_c.jpg>","<img src=images/questions/4_a.jpg>","<img src=images/questions/4_b.jpg>","<img src=images/questions/4_c.jpg>","<img src=images/questions/4_d.jpg>","<img src=images/questions/4_e.jpg>","Figural Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("5","1","Verbal","<b>First</b> is to original as <b>only</b> is to ---","unique","special","unique","expensive","many","last","Verbal Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("6","3","Verbal","<img src=images/questions/6_q.jpg>","<img src=images/questions/6_c.jpg>","<img src=images/questions/6_a.jpg>","<img src=images/questions/6_b.jpg>","<img src=images/questions/6_c.jpg>","<img src=images/questions/6_d.jpg>","<img src=images/questions/6_e.jpg>","Verbal Comprehension");<|||||||>
INSERT INTO tbl_questions VALUES("7","3","NonVerbal","<img src=images/questions/7_q.jpg>","<img src=images/questions/7_e.jpg>","<img src=images/questions/7_a.jpg>","<img src=images/questions/7_b.jpg>","<img src=images/questions/7_c.jpg>","<img src=images/questions/7_d.jpg>","<img src=images/questions/7_e.jpg>","Quantitative Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("8","3","NonVerbal","<img src=images/questions/8_q.jpg>","<img src=images/questions/8_c.jpg>","<img src=images/questions/8_a.jpg>","<img src=images/questions/8_b.jpg>","<img src=images/questions/8_c.jpg>","<img src=images/questions/8_d.jpg>","<img src=images/questions/8_e.jpg>","Figural Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("9","1","NonVerbal","What number comes next in this series?   1    6    10    13    15    ?","16","14","16","17","18","19","Quantitative Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("10","1","Verbal","The opposite of <b>confinement</b> is ----","freedom","recognition","satisfaction","cooperation","dedication","freedom","Verbal Comprehension");<|||||||>
INSERT INTO tbl_questions VALUES("11","1","Verbal","Which word does <i>not</i> go with the other four?","polite","honest","polite","truthful","open","frank","Verbal Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("12","3","NonVerbal","<img src=images/questions/12_q.jpg>","<img src=images/questions/12_d.jpg>","<img src=images/questions/12_a.jpg>","<img src=images/questions/12_b.jpg>","<img src=images/questions/12_c.jpg>","<img src=images/questions/12_d.jpg>","<img src=images/questions/12_e.jpg>","Figural Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("13","1","Verbal","There are five houses in a row. One house is gree. Two yellow houses are next to each other. The end house is red. The middle house is blue. What colors are the houses that are farthest apart?","Red and yellow","Red and yellow","Red and blue","Yellow and blue","Green and yellow","Blue and green","Verbal Comprehension");<|||||||>
INSERT INTO tbl_questions VALUES("14","1","Verbal","An enclosure always has ---","sides","an entrance","ventilation","sides","a roof","windows","Verbal Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("15","1","Verbal","Choose the word that <i>best</i> completes this sentence: <br> Faulty reasoning generally results in _________ conclusions.","erroneous","intelligent","valid","eccentric","erroneous","offensive","Verbal Comprehension");<|||||||>
INSERT INTO tbl_questions VALUES("16","3","NonVerbal","<img src=images/questions/16_q.jpg>","<img src=images/questions/16_d.jpg>","<img src=images/questions/16_a.jpg>","<img src=images/questions/16_b.jpg>","<img src=images/questions/16_c.jpg>","<img src=images/questions/16_d.jpg>","<img src=images/questions/16_e.jpg>","Quantitative Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("17","3","NonVerbal","<img src=images/questions/17_q.jpg>","<img src=images/questions/17_c.jpg>","<img src=images/questions/17_a.jpg>","<img src=images/questions/17_b.jpg>","<img src=images/questions/17_c.jpg>","<img src=images/questions/17_d.jpg>","<img src=images/questions/17_e.jpg>","Quantitative Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("18","3","Verbal","<img src=images/questions/18_q.jpg>","<img src=images/questions/18_b.jpg>","<img src=images/questions/18_a.jpg>","<img src=images/questions/18_b.jpg>","<img src=images/questions/18_c.jpg>","<img src=images/questions/18_d.jpg>","<img src=images/questions/18_e.jpg>","Verbal Comprehension");<|||||||>
INSERT INTO tbl_questions VALUES("19","3","NonVerbal","<img src=images/questions/19_q.jpg>","<img src=images/questions/19_c.jpg>","<img src=images/questions/19_a.jpg>","<img src=images/questions/19_b.jpg>","<img src=images/questions/19_c.jpg>","<img src=images/questions/19_d.jpg>","<img src=images/questions/19_e.jpg>","Figural Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("20","1","Verbal","<b>Increase</b> is to <b>reveal</b> as <b>decrease</b> is to ----","conceal","reduce","concede","refuse","conceal","disclose","Verbal Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("21","1","Verbal","Robert buys 14 cans of dog food every week for his dogs, who each eat one can a day. If Robert has twice as many cats as dogs, how many cats does he have?","4","2","4","6","7","8","Verbal Comprehension");<|||||||>
INSERT INTO tbl_questions VALUES("22","3","NonVerbal","<img src=images/questions/22_q.jpg>","<img src=images/questions/22_b.jpg>","<img src=images/questions/22_a.jpg>","<img src=images/questions/22_b.jpg>","<img src=images/questions/22_c.jpg>","<img src=images/questions/22_d.jpg>","<img src=images/questions/22_e.jpg>","Figural Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("23","1","NonVerbal","What comes next in this series?    10C    8A    12E    10C    14G?","12E","12E","12G","14E","16I","18K","Quantitative Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("24","1","Verbal","Paul was born in 1970. Dick was born in 1972. If John is younger than Dick, then we know that ---","Dick is younger than Paul and older than John","Dick is younger than Paul and older than John","Paul is older than Dick and younger than John","Paul is younger than Dick and older than John","Paul is younger than Dick and John","Dick is older than Paul and younger than John","Verbal Comprehension");<|||||||>
INSERT INTO tbl_questions VALUES("25","1","Verbal","Whice word goes <i>most clearly</i> with: <b>peaceful    serene    tranquil</b>?","calm","joyous","monotonous","emotional","sensible","calm","Verbal Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("26","3","NonVerbal","<img src=images/questions/26_q.jpg>","<img src=images/questions/26_c.jpg>","<img src=images/questions/26_a.jpg>","<img src=images/questions/26_b.jpg>","<img src=images/questions/26_c.jpg>","<img src=images/questions/26_d.jpg>","<img src=images/questions/26_e.jpg>","Quantitative Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("27","3","Verbal","<img src=images/questions/27_q.jpg>","<img src=images/questions/27_c.jpg>","<img src=images/questions/27_a.jpg>","<img src=images/questions/27_b.jpg>","<img src=images/questions/27_c.jpg>","<img src=images/questions/27_d.jpg>","<img src=images/questions/27_e.jpg>","Verbal Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("28","1","Verbal","The opposite of <b>discord</b> is ---","harmony","harmony","grace","tradition","silence","friendliness","Verbal Comprehension");<|||||||>
INSERT INTO tbl_questions VALUES("29","3","NonVerbal","<img src=images/questions/29_q.jpg>","<img src=images/questions/29_e.jpg>","<img src=images/questions/29_a.jpg>","<img src=images/questions/29_b.jpg>","<img src=images/questions/29_c.jpg>","<img src=images/questions/29_d.jpg>","<img src=images/questions/29_e.jpg>","Figural Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("30","3","NonVerbal","<img src=images/questions/30_q.jpg>","<img src=images/questions/30_c.jpg>","<img src=images/questions/30_a.jpg>","<img src=images/questions/30_b.jpg>","<img src=images/questions/30_c.jpg>","<img src=images/questions/30_d.jpg>","<img src=images/questions/30_e.jpg>","Quantitative Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("31","3","NonVerbal","<img src=images/questions/31_q.jpg>","<img src=images/questions/31_d.jpg>","<img src=images/questions/31_a.jpg>","<img src=images/questions/31_b.jpg>","<img src=images/questions/31_c.jpg>","<img src=images/questions/31_d.jpg>","<img src=images/questions/31_e.jpg>","Figural Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("32","3","NonVerbal","<img src=images/questions/32_q.jpg>","<img src=images/questions/32_e.jpg>","<img src=images/questions/32_a.jpg>","<img src=images/questions/32_b.jpg>","<img src=images/questions/32_c.jpg>","<img src=images/questions/32_d.jpg>","<img src=images/questions/32_e.jpg>","Figural Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("33","1","Verbal","<b>Possible</b> is to <b>maybe</b> as <b>probable</b> is to ---","likely","gradually","hopefully","certainly","eventually","likely","Verbal Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("34","1","NonVerbal","Mr. and Mrs. DiNapoli have two sons and three daughters. When the whole family is together for dinner, they have to bring one extra chair to the table, How many chairs do they usually have around the table?","6","4","5","6","7","8","Quantitative Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("35","1","Verbal","The opposite of <b>moderate</b> is ----","extreme","sudden","swift","treacherous","violent","extreme","Verbal Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("36","3","NonVerbal","<img src=images/questions/36_q.jpg>","<img src=images/questions/36_d.jpg>","<img src=images/questions/36_a.jpg>","<img src=images/questions/36_b.jpg>","<img src=images/questions/36_c.jpg>","<img src=images/questions/36_d.jpg>","<img src=images/questions/36_e.jpg>","Quantitative Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("37","3","NonVerbal","<img src=images/questions/37_q.jpg>","<img src=images/questions/37_d.jpg>","<img src=images/questions/37_a.jpg>","<img src=images/questions/37_b.jpg>","<img src=images/questions/37_c.jpg>","<img src=images/questions/37_d.jpg>","<img src=images/questions/37_e.jpg>","Figural Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("38","1","Verbal","Every country must have ----","boundaries","coasts","a president","boundaries","a navy","a flag","Verbal Comprehension");<|||||||>
INSERT INTO tbl_questions VALUES("39","1","NonVerbal","What number is missing from this seires?    4    8    6    12    10    ?    18    36","20","8","14","16","20","24","Figural Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("40","1","Verbal","Assume that ---- <br> All <b>A</b>s are <b>C</b>s.<br>Some <b>D</b>s are <b>C</b>s. No <b>B</b>s. are <b>C</b>s.","no <b>A</b>s are <b>B</b>s","no <b>A</b>s are <b>D</b>s","no <b>A</b>s are <b>B</b>s","some <b>B</b>s are <b>D</b>s","some <b>A</b>s are both <b>C</b>s and <b>D</b>s","no <b>D</b>s are <b>B</b>s","Verbal Comprehension");<|||||||>
INSERT INTO tbl_questions VALUES("41","3","NonVerbal","<img src=images/questions/41_q.jpg>","<img src=images/questions/41_e.jpg>","<img src=images/questions/41_a.jpg>","<img src=images/questions/41_b.jpg>","<img src=images/questions/41_c.jpg>","<img src=images/questions/41_d.jpg>","<img src=images/questions/41_e.jpg>","Figural Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("42","3","Verbal","<img src=images/questions/42_q.jpg>","<img src=images/questions/42_b.jpg>","<img src=images/questions/42_a.jpg>","<img src=images/questions/42_b.jpg>","<img src=images/questions/42_c.jpg>","<img src=images/questions/42_d.jpg>","<img src=images/questions/42_e.jpg>","Verbal Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("43","3","NonVerbal","<img src=images/questions/43_q.jpg>","<img src=images/questions/43_a.jpg>","<img src=images/questions/43_a.jpg>","<img src=images/questions/43_b.jpg>","<img src=images/questions/43_c.JPG>","<img src=images/questions/43_d.jpg>","<img src=images/questions/43_e.JPG>","Figural Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("44","3","NonVerbal","<img src=images/questions/44_q.jpg>","<img src=images/questions/44_d.JPG>","<img src=images/questions/44_a.jpg>","<img src=images/questions/44_b.jpg>","<img src=images/questions/44_c.jpg>","<img src=images/questions/44_d.JPG>","<img src=images/questions/44_e.jpg>","Quantitative Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("45","1","Verbal","Whice word goes <i>most clearly</i> with: <b>forward    sideways    down</b>?","up","top","up","above","over","beyond","Verbal Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("46","1","NonVerbal","What number is equal to one-third of the difference between the squares of ten and eight?","12","3","6","12","18","36","Quantitative Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("47","1","NonVerbal","What letter comes next in this series?    H    I    K    L    N    O    ?","Q","M","P","Q","R","S","Figural Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("48","3","NonVerbal","<img src=images/questions/48_q.jpg>","<img src=images/questions/48_a.JPG>","<img src=images/questions/48_a.JPG>","<img src=images/questions/48_b.jpg>","<img src=images/questions/48_c.JPG>","<img src=images/questions/48_d.jpg>","<img src=images/questions/48_e.jpg>","Figural Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("49","3","NonVerbal","<img src=images/questions/49_q.JPG>","<img src=images/questions/49_c.jpg>","<img src=images/questions/49_a.JPG>","<img src=images/questions/49_b.jpg>","<img src=images/questions/49_c.jpg>","<img src=images/questions/49_d.JPG>","<img src=images/questions/49_e.JPG>","Quantitative Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("50","1","Verbal","<b>Electricity</b> is to <b>light bulb</b> as ----","fuel is to engine","furnace is to heat","steam is to radiator","water is to dam","fuel is to engine","smoke is to fine","Verbal Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("51","3","NonVerbal","<img src=images/questions/51_q.JPG>","<img src=images/questions/51_b.JPG>","<img src=images/questions/51_a.JPG>","<img src=images/questions/51_b.JPG>","<img src=images/questions/51_c.JPG>","<img src=images/questions/51_d.jpg>","<img src=images/questions/51_e.JPG>","Quantitative Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("52","3","Verbal","<img src=images/questions/52_q.jpg>","<img src=images/questions/52_c.JPG>","<img src=images/questions/52_a.jpg>","<img src=images/questions/52_b.jpg>","<img src=images/questions/52_c.JPG>","<img src=images/questions/52_d.jpg>","<img src=images/questions/52_e.JPG>","Verbal Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("53","1","Verbal","There can be no message if there is no ----","thought","word","note","messenger","thought","pencil","Verbal Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("54","3","NonVerbal","<img src=images/questions/54_q.jpg>","<img src=images/questions/54_a.jpg>","<img src=images/questions/54_a.jpg>","<img src=images/questions/54_b.jpg>","<img src=images/questions/54_c.jpg>","<img src=images/questions/54_d.JPG>","<img src=images/questions/54_e.JPG>","Figural Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("55","1","Verbal","Choose the words that <i>best</i> complete this sentence: <br> The evidence against him was ________ so the charge were _________","unsupported ---- dismissed","convincing ---- dropped","feeble ---- extended","overwhelming ---- reduced","damaging ---- withdrawn","unsupported ---- dismissed","Verbal Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("56","3","NonVerbal","<img src=images/questions/55_q.JPG>","<img src=images/questions/55_b.JPG>","<img src=images/questions/55_a.JPG>","<img src=images/questions/55_b.JPG>","<img src=images/questions/55_c.JPG>","<img src=images/questions/55_d.JPG>","<img src=images/questions/55_e.JPG>","Figural Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("57","1","Verbal","The opposite of <b>scarcity</b> is ----","abundance","necessity","bonus","privilage","abundance","expansion","Verbal Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("58","1","Verbal","In a foreign language <b>tana dona meka</b> means <b>very cold water, tana neta</b> means <b>hot water,</b> and <b>dona bela</b> means <b>very good.</b> Whice word means <b>cold</b>?","meka","dona","neta","tana","bela","meka","Verbal Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("59","3","NonVerbal","<img src=images/questions/59_q.JPG>","<img src=images/questions/59_d.jpg>","<img src=images/questions/59_a.JPG>","<img src=images/questions/59_b.JPG>","<img src=images/questions/59_c.JPG>","<img src=images/questions/59_d.jpg>","<img src=images/questions/59_e.jpg>","Figural Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("60","1","NonVerbal","What number comes next in this series?   5    11    16    20    23    ?","25","24","25","27","28","29","Quantitative Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("61","1","Verbal","Which word does <i>not</i> go with the other four?","frightened","dangerous","risky","hazardous","unsafe","frightened","Verbal Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("62","3","Verbal","<img src=images/questions/62_q.JPG>","<img src=images/questions/62_b.JPG>","<img src=images/questions/62_a.JPG>","<img src=images/questions/62_b.JPG>","<img src=images/questions/62_c.JPG>","<img src=images/questions/62_d.JPG>","<img src=images/questions/62_e.JPG>","Verbal Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("63","3","NonVerbal","<img src=images/questions/63_q.JPG>","<img src=images/questions/63_b.jpg>","<img src=images/questions/63_a.JPG>","<img src=images/questions/63_b.jpg>","<img src=images/questions/63_c.JPG>","<img src=images/questions/63_d.JPG>","<img src=images/questions/63_e.JPG>","Figural Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("64","3","NonVerbal","<img src=images/questions/64_q.JPG>","<img src=images/questions/64_c.jpg>","<img src=images/questions/64_a.JPG>","<img src=images/questions/64_b.JPG>","<img src=images/questions/64_c.jpg>","<img src=images/questions/64_d.jpg>","<img src=images/questions/64_e.JPG>","Quantitative Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("65","1","Verbal","A cloud is always ----","humid","humid","fluffy","white","big","high","Verbal Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("66","3","Verbal","<img src=images/questions/66_q.JPG>","<img src=images/questions/66_d.JPG>","<img src=images/questions/66_a.JPG>","<img src=images/questions/66_b.JPG>","<img src=images/questions/66_c.JPG>","<img src=images/questions/66_d.JPG>","<img src=images/questions/66_e.jpg>","Verbal Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("67","3","Verbal","<img src=images/questions/67_q.jpg>","<img src=images/questions/67_e.jpg>","<img src=images/questions/67_a.JPG>","<img src=images/questions/67_b.JPG>","<img src=images/questions/67_c.JPG>","<img src=images/questions/67_d.jpg>","<img src=images/questions/67_e.jpg>","Verbal Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("68","3","Verbal","<img src=images/questions/68_q.JPG>","<img src=images/questions/68_e.jpg>","<img src=images/questions/68_a.JPG>","<img src=images/questions/68_b.JPG>","<img src=images/questions/68_c.JPG>","<img src=images/questions/68_d.jpg>","<img src=images/questions/68_e.jpg>","Verbal Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("69","3","NonVerbal","<img src=images/questions/69_q.jpg>","<img src=images/questions/69_c.JPG>","<img src=images/questions/69_a.JPG>","<img src=images/questions/69_b.jpg>","<img src=images/questions/69_c.JPG>","<img src=images/questions/69_d.JPG>","<img src=images/questions/69_e.JPG>","Quantitative Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("70","3","Verbal","<img src=images/questions/70_q.jpg>","<img src=images/questions/70_a.jpg>","<img src=images/questions/70_a.jpg>","<img src=images/questions/70_b.jpg>","<img src=images/questions/70_c.jpg>","<img src=images/questions/70_d.jpg>","<img src=images/questions/70_e.jpg>","Verbal Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("71","1","NonVerbal","what number divided by three is equal to ten plus two?","36","12","13","24","30","36","Quantitative Reasoning");<|||||||>
INSERT INTO tbl_questions VALUES("72","1","Verbal","Choose the words that <i>best</i> complete this sentence: <br> Although Jamie s grades were _________, her parents were ________","acceptable ---- disappointed","excellent ---- delighted","terrible ---- furious","poor ---- dissatisfied","acceptable ---- disappointed","superior ---- interested","Verbal Comprehension");<|||||||>

