<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your OTP Code {{ $otp }} - Northeastern College</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 20px;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            background-color: #ffffff;
            padding: 30px;
            border-radius: 15px;
            box-shadow: 0 0 15px rgba(0, 0, 0, 0.1);
            border: 1px solid #dddddd;
        }
        .mail-envelope {
            padding: 30px;
            border-radius: 15px;
            background-color: #f9f9f9;
            position: relative;
        }
        .logo {
            text-align: center;
            margin-bottom: 20px;
        }
        .logo img {
            width: 100%; 
            max-width: 350px;
        }
        .header {
            text-align: center;
            color: #333333;
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 20px;
        }
        .otp {
            font-size: 48px;
            color: #048e2b;
            font-weight: bold;
            text-align: center;
            margin: 30px 0;
        }
        .content {
            text-align: center;
            font-size: 16px;
            color: #555555;
        }
        .expiry {
            margin-top: 20px;
            color: #e63946;
            font-size: 14px;
            text-align: center;
        }
        .footer {
            text-align: center;
            margin-top: 40px;
            font-size: 12px;
            color: #999999;
        }
        /* Adding visual envelope-like lines */
        .envelope-top {
            border-top: 5px solid #048e2b;
            position: relative;
            top: -10px;
        }
        .envelope-bottom {
            border-bottom: 5px solid #048e2b;
            position: relative;
            bottom: -10px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="envelope-top"></div>

        <div class="mail-envelope">
            <div class="logo">
                <img src="{{asset('img/header-logo.png')}}" alt="Northeastern College Logo">
            </div>

            <h1 class="header">Your One-Time Password (OTP)</h1>

            <p class="otp">{{ $otp }}</p>

            <p class="content">Use the OTP code above to complete your login process. If you didn’t request this, please ignore this email.</p>

            <p class="expiry">⚠️ This OTP will expire in 5 minutes. ⚠️</p>
        </div>

        <div class="envelope-bottom"></div>

        <div class="footer">
            <p>&copy; {{ date('Y') }} Northeastern College School Ability Test. All rights reserved.</p>
            <p>Generated by the School Ability Test system.</p>
        </div>
    </div>
</body>
</html>
